---
- name: Create final AMI from intermediate
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    base_dir: "{{ lookup('pipe', 'git rev-parse --show-toplevel') }}"
    last_commit: "{{ lookup('pipe', 'git log -n 1') }}"
    timestamp: "{{ lookup('pipe', 'date +%s') }}"

  tasks:
    - name: Copy final AMI
      ec2_ami_copy:
        aws_access_key: "{{ cloud_env[cloud].access_key | default(omit) }}"
        aws_secret_key: "{{ secrets[cloud].secret_access_key | default(omit) }}"
        name: "{{ template + '-CIStested-' + timestamp }}"
        description: "{{ last_commit }}"
        source_image_id: "{{ ami_info.image_id }}"
        encrypted: "{{ base_templates[cloud_env[cloud].type][template].encrypt|default(false|bool) }}"
        kms_key_id: "{{ base_templates[cloud_env[cloud].type][template].kms_key|default(omit) }}"
        region: "{{ cloud_env[cloud].region }}"
        source_region: "{{ cloud_env[cloud].region }}"
        wait: yes

    - name: Delete candidate AMI (we don't need it anymore)
      ec2_ami:
        aws_access_key: "{{ cloud_env[cloud].access_key | default(omit) }}"
        aws_secret_key: "{{ secrets[cloud].secret_access_key | default(omit) }}"
        image_id: "{{ ami_info.image_id }}"
        region: "{{ cloud_env[cloud].region }}"
        delete_snapshot: yes
        state: absent

#    - name: Capture final AMI
#      ec2_ami:
#        aws_access_key: "{{ cloud_env[cloud].access_key | default(omit) }}"
#        aws_secret_key: "{{ secrets[cloud].secret_access_key | default(omit) }}"
#        description: "{{ last_commit }}"
#        instance_id: "{{ ec2_instance.instances[0].instance_id }}"
#        region: "{{ cloud_env[cloud].region }}"
#        name: "{{ template + '-CIStested-' + timestamp }}"
#        wait: true
#        state: present
#        launch_permissions:
#          user_ids: "{{ cloud_env[cloud].launch_ids }}"
#      register: ami_info
