  - name: "Power Off  VM ({{ source_vm }}) if it exists"
    vmware_guest:
      hostname: "{{ cloud_params.vcenter.host }}"
      username: "{{ cloud_params.vcenter.username }}"
      password: "{{ cloud_password }}"
      validate_certs: "{{ cloud_params.vcenter.validate_certs }}"
      datacenter: "{{ cloud_params.vcenter.datacenter }}"
      folder: "/{{ cloud_params.vcenter.datacenter }}/vm/{{ source_folder }}"
      name: "{{ source_vm }}"
      state: poweredoff
    ignore_errors: yes
    changed_when: false

  - name: "Remove VM ({{ source_vm }}) if it exists"
    vmware_guest:
      hostname: "{{ cloud_params.vcenter.host }}"
      username: "{{ cloud_params.vcenter.username }}"
      password: "{{ cloud_password }}"
      validate_certs: "{{ cloud_params.vcenter.validate_certs }}"
      datacenter: "{{ cloud_params.vcenter.datacenter }}"
      folder: "/{{ cloud_params.vcenter.datacenter }}/vm/{{ source_folder }}"
      name: "{{ source_vm }}"
      state: absent
