---
  - name: Wait for the VM to be powered off
    vmware_guest_facts:
      hostname: "{{ cloud_params.vcenter.host }}"
      username: "{{ cloud_params.vcenter.username }}"
      password: "{{ cloud_password }}"
      validate_certs: "{{ cloud_params.vcenter.validate_certs }}"
      datacenter: "{{ cloud_params.vcenter.datacenter }}"
      folder: "/{{ cloud_params.vcenter.datacenter }}/vm/{{ source_folder }}"
      name: "{{ source_vm }}"
    register: _vm_facts
    retries: 100
    until: _vm_facts.instance.hw_power_status == "poweredOff"
    ignore_errors: true



