---
- name: install web packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ httpd_components }}"

- name: Enable httpd service
  service:
    name: httpd
    enabled: yes
    state: started

- name: Turn TRACE off
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    regexp: "^#?TraceEnable"
    line: "TraceEnable off"
  notify:
    - Reload httpd

- name: Set SSL options
  copy:
    src: include/ssl.conf
    dest: /etc/httpd/conf.d/ssl.conf
    mode: 0644
  notify:
    - Reload httpd

- name: Open firewall ports
  firewalld:
    zone: public
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
    - ssh
    - http
    - https
