version: 2
jobs:
  build:
    docker:
      - image: imagecloudio/plant:2018.06.22
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
