---
  - name: Cleanup explicitly
    hosts: localhost
    connection: local
    gather_facts: false

    vars:
      base_dir      : "{{ lookup('pipe','git rev-parse --show-toplevel')}}"

    tasks:
      - name: Check required parameters
        assert:
          that:
            - cloud is defined
            - cloud_type is defined

      - name: Check cloud type
        assert:
          that: 'cloud_type == cloud_env[cloud].type'
          msg: "The cloud type specified doesn't match the cloud type of the selected cloud. Due to a limitation in Ansible, it's currently not possible to set it through variable assignments in the playbook. "

  - import_playbook: "{{ cloud_type }}/99-cleanup.yml"


